export const GET_SLIDERS='GET_SLIDERS'
export const ADD_NEW_SLIDER='ADD_NEW_SLIDER'
export const DELETE_SLIDER='DELETE_SLIDER'
export const EDIT_SLIDER='EDIT_SLIDER'

export const TOGGLE_VISIBLE='TOGGLE_VISIBLE'

export const GET_ROLES='GET_ROLES'
export const ADD_NEW_ROLE='ADD_NEW_ROLE'
export const DELETE_ROLE='DELETE_ROLE'
export const EDIT_ROLE='EDIT_ROLE'

export const GET_USERS='GET_USERS'
export const ADD_NEW_USER='ADD_NEW_USER'
export const DELETE_USER='DELETE_USER'
export const EDIT_USER='EDIT_USER'

export const GET_SOCIALMEDIAS='GET_SOCIALMEDIAS'
export const ADD_NEW_SOCIALMEDIA='ADD_NEW_SOCIALMEDIA'
export const DELETE_SOCIALMEDIA='DELETE_SOCIALMEDIA'
export const EDIT_SOCIALMEDIA='EDIT_SOCIALMEDIA'

export const GET_MEDIAS='GET_MEDIAS'
export const ADD_NEW_MEDIA='ADD_NEW_MEDIA'
export const DELETE_MEDIA='DELETE_MEDIA'
export const EDIT_MEDIA='EDIT_MEDIA'

export const GET_EXPERTS='GET_EXPERTS'
export const ADD_NEW_EXPERT='ADD_NEW_EXPERT'
export const DELETE_EXPERT='DELETE_EXPERT'
export const EDIT_EXPERT='EDIT_EXPERT'

export const GET_COMPANY_INTROS='GET_COMPANY_INTROS'
export const ADD_NEW_COMPANY_INTRO='ADD_NEW_COMPANY_INTRO'
export const DELETE_COMPANY_INTRO='DELETE_COMPANY_INTRO'
export const EDIT_COMPANY_INTRO='EDIT_COMPANY_INTRO'

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
export const SET_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
export const SET_PAGINATION = "SET_PAGINATION";