export const GET_SLIDERS='GET_SLIDERS'
export const ADD_NEW_SLIDER='ADD_NEW_SLIDER'
export const DELETE_SLIDER='DELETE_SLIDER'
export const EDIT_SLIDER='EDIT_SLIDER'

export const TOGGLE_VISIBLE='TOGGLE_VISIBLE'

export const GET_USERS='GET_USERS'
export const ADD_NEW_USER='ADD_NEW_USER'
export const DELETE_USER='DELETE_USER'
export const EDIT_USER='EDIT_USER'

export const GET_EXPERTS='GET_EXPERTS'
export const ADD_NEW_EXPERT='ADD_NEW_EXPERT'
export const DELETE_EXPERT='DELETE_EXPERT'
export const EDIT_EXPERT='EDIT_EXPERT'

export const GET_COMPANY_INTROS='GET_COMPANY_INTROS'
export const ADD_NEW_COMPANY_INTRO='ADD_NEW_COMPANY_INTRO'
export const DELETE_COMPANY_INTRO='DELETE_COMPANY_INTRO'
export const EDIT_COMPANY_INTRO='EDIT_COMPANY_INTRO'